---
title: "I was Part of the Problem"
date: '2017-10-18'
categories: [metoo, academia]
subtitle: |
  Why do so many men think it's OK to lavish unwanted attention on women who don't want it?
---

## TL;DR

With the recent charges of sexual harassment against some high-profile individuals,
and so many women coming forward with #metoo (and the understanding that this 
is really something almost *all* women have faced), I realized that my younger self
was #partoftheproblem. I think many other men are part of the problem, **even though they might not think so**. I didn't think I was part of the problem
either. I hope that other men might read this and critically evaluate if they
are #partoftheproblem. I also hope and pray that my own sons will do better
at this if I teach them right.

## How Could I Be?

Let me be up front. I have never **sexually assaulted** anyone, let alone
considered such a thing. But that's not really the problem, because the way
I acted towards women, I think they may have been scared that I might, as 
I have put tons of **unwanted attention** on several
women over the years, starting with when I was 12 years old, in the sixth grade.

I also want to be clear, I was a horrible guy friend to women 
(even if they didn't think so). If I knew a girl had a boyfriend,
well then, I would **not** even consider trying to hit on or express interest in
that girl, and I was "friends" with plenty of women over the course of my school
years who had boyfriends. But in **most** cases I secretly hoped they might dump their
boyfriends and go out with me instead. Also, if I knew they didn't have 
a boyfriend, and I found them remotely attractive, then I would do all I could
to try to become friends with them in the **hope to eventually become their boyfriend**.
So, my sole reason for being friends with women, really, was to eventually
become romantically involved. That was my primary motivation. Looking back on it
now, it makes me sick.

I've never had a woman tell me she was assaulted by anyone either, but given my
past behavior, even if someone I knew had, I don't think my actions made me someone
that a woman would trust to tell. 

Let me give you some examples of my behavior.

## Grade School

In 6th grade, I decided that I wanted a girlfriend, and I picked out one girl in my class who
I wanted to be my girlfriend. I am very sure I never asked her out, to be my girlfriend,
but I made sure to spend tons of time with her, and if I recall correctly, she eventually got
the gist of my interest, and told me **very clearly she wasn't interested**. 
But **her telling me no did not stop my unwanted advances** or attention. I am sure that I made
her very uncomfortable the rest of that grade.

In middle school (7-9 at the time), I pretty much continued this process unabated. I would latch onto a girl
that I found attractive, and make her the target of my affections, and pour out my unwanted
attention upon her, **not taking no for an answer**. I only stopped
after long periods of continued rejection, or when that person acquired a 
significant other. Although not an excuse for my actions, 
my tactics and hopes were largely fueled by rampaging hormones, way too many
romantic comedies where the nice guy always got the girl by virtue
of sheer persistence (this was the 90's), and nascent exposure to pornography.

I would find out girls numbers and call them without being asked. I would know
where these girls were at all times through the day, even during lunch and
between classes. I would find any excuse to be near them. Every sock-hop (weekly
lunch time dance on gym floor) I would ask these girls to dance with me. I would
give them valentines cards, Christmas cards, etc, in **the hopes that they would realize what a great guy I was and go out with me.**

Just so we are clear, none of this got me any dates in grade school.

## Undergraduate

Now I've graduated high-school, I'm heading off to a local university, with lots
of women. I made lots of friends with girls who had boyfriends, in fact I think
my circle of friends had way more girls in it than guys. But, I was always finding
one girl who I wanted to date, and would make sure to spend extra time around them,
helping them whenever possible, etc, and dropping subtle and not so subtle hints
that I wanted to be their boyfriend. And there was always the hope that someone
would break-up with their current boyfriend and find me, the faithful friend,
waiting to comfort them.

Over the course of this time, I had three women agree to be my date. Two of those
did not result in an actual date, because I started acting like a stalker after 
they said yes, and they wisely stayed away. In the third case, we went out twice,
but me calling at random hours, and showing up at her house un-announced because
I thought she was really sad freaked her out, and she stopped talking to my
creepy, stalkerish, clingy self.

## Post-Graduate

Somehow, it seems, by the time I got to my PhD, I had **mostly** given up on 
finding a girlfriend, settling down and getting married (really, that was my goal). 
I say mostly. I don't know
if I hadn't met my now spouse in the first couple of months of my PhD that I
would not have continued making unwanted advances on the women in my PhD program.
(By the way, I met my spouse outside of work, at a Church actually, and was introduced
by a mutual friend. In the 13 years I've known her, there are only a handful of days
we haven't talked to each other since we went on our first date).

## The Real Problem

And this is the **real** problem. Too many men, my past self included, think women owe them something for being
their friend, for being a **nice guy**. For giving them any kind of attention,
or any kind of help. Too many men believe these things, and then use their power and 
prestige, to demand things of women. Guys, **women don't owe you anything.** They
definitely don't owe you sex or reciprocated romantic interest because of something
you did for them. They are another person worthy of respect, simply because they
are a person. 

In addition, real life is not a romantic comedy. Non-romantic friendships are a good thing, 
because we need other peoples perspectives in our lives. So, if a woman tells you 
**no, she doesn't want to date you**, accept it, and move on. Don't make it awkward, especially if you are
in the same work environment. 
**Don't assume that a woman is romantically interested just because she is friendly.** I know, radical thought. Maybe try being friends, colleagues, whatever with
no romantic intentions, and no expectations of them either. Don't be #partoftheproblem.

## Solutions

Teach your children that they can be friends with people of the opposite sex
without being romantically involved, especially as they hit puberty. Teach
them that **no means no**, not **no means maybe in 3 weeks**, or 
**no means maybe if I try hard enough**. And if you see other men engaging in putting
unwanted attention on women, call them out on it, **whatever form it may take**.
I wish someone had said something to me.

## Caveats

I realize that our general culture is really #partoftheproblem, when we have
highly sexualized advertising (especially of women to men), and the idea
that **boys will be boys**, tell jokes about sexual assault, and propagate
the idea that **women want it**, based on how they act or dress. Those are all wrong
too, and our culture needs to change.

I also realize that some of what I describe
about myself is rather mild in comparison to much of what gets reported, but
that's not the point. It is still unwanted attention, and I didn't know how
to take no for an answer. Those women **didn't want my attention**,
and I couldn't accept that. If I had a different temperament, I don't know what
I would have done. Enough people realized it that some friends in Undergrad
stopped being around me, but no one ever told me that what I was doing was
wrong, and my parents weren't involved enough in my so-called love life to know
what was going on. If they had, I think they would have told me to knock it off
and stop being an idiot.
