---
title: "First Open Post-Publication Peer Review, with Credit!"
date: 2015-03-25
categories: [open-science, peer-review, publications]
subtitle: |
  A story about my first open peer-review.
---

## TL;DR

Reviewed [Jason McDermott's](https://twitter.com/@biodataganache) [MDRPred paper](http://f1000research.com/articles/4-60/v1) on F1000Research!, where my review is posted along side the paper, [with a DOI](http://f1000research.com/articles/4-60/v1#referee-response-7889), completely in the open with my name attached. Was a pleasant experience, aided by the fact that Jason wrote a good paper.

## F1000Research!

[F1000Research!](http://f1000research.com/) is a new publishing startup from F1000 that has a model of post-publication peer review, whereby upon submission the manuscript undergoes basic quality checks (no real editorial control), and then is published. Once the article is published, reviewers are invited to review, and they have 10 days to submit their review. Reviews are signed, and given a DOI. Reviewers are asked to assign one of **Approved**, **Approved with Reservations**, **Not Approved** status to the article.

When the article gets two revieweres giving **Approved** status (likely after at least one round of review and resubmission), then it will be submitted to PubMed for indexing. 

## How Did I End Up Reviewing This??

Long story short, I've been following Jason on twitter for a while, and I happened to see him tweet and blog about trying to get an F1000Research article up as a citeable supporting publication for a grant going in. I thought it was a nifty idea, and although I actually at the time did not have much of an idea of what Jason's research actually involved, communicated with him that when the article went live I would be willing to be recommended as a reviewer. Imagine my surprise that I actually had enough domain knowledge that I could actually review the article. 

That is saying something, given that the paper has a neat combination of genetic algorithms, regular expressions, and protein function prediction (really, you should go give it a read). By the way, this is also the first paper I've reviewed in a long time that did not have serious methodological problems, or where claims are made with no substantiation, and I could not identify any serious statistical issues.

## The Open Part

Although I don't do a lot of reviewing, I had to admit that this was one of the best reviewing assignments I've had in a while. Although I believe that peer review is essential to science, and it needs to be more open (I've started signing my reviews for other journals), this was the first time I knew my review was open (my name would be known to the authors' by default) and public. I have to say that this likely improved the care and thoroughness in doing the actual review as I went through the article, given that both the authors and anyone else who comes across the article and my review can see if the issues I raise are real, or if I'm trying to make myself look good. And my name will be publicly associated with it!

Note that this **openness** did not keep me from criticizing particular aspects of the paper. There are lots of things that need to be changed in the article before I will give it an **Approved** status, and I laid those out in my review.

## PostPublication

I really appreciated that I get to review a **published** article, because it means that the whole thing is typeset, figures and tables are in their logical place (not at the end of the document!!!), the line spacing is readable, etc. Note to other publishers, at least let authors put the figures in-line for review if you are not going to type-set the article before it goes to reviewers.

## Disclaimers

I was given an F1000Research! t-shirt as a reward for commenting on a [blog-post](http://blog.f1000research.com/2013/08/23/peer-review-credit-where-credits-due/#comment-1020559658) regarding incentives for peer-review. I like the shirt. Having done my review, I am also eligible to get a 50% discount on the article processing charges if I submit an article to F1000Research in the next 12 months.
