---
title: "Researcher Discoverability"
date: 2014-06-19
categories: [github, open-science, academia, research]
subtitle: |
  Why do we need corporate products to enhance "researcher discoverability"?
---

University of Kentucky (UK) recently partnered with the discovery portal [KNODE](https://search.knodeinc.com/ukentucky/index.action), for helping others to discover potential collaborators at UK. KNODE looks like a large corporate venture, that is probably costing a large amount of capital to the university (and other places that use it). I wonder if the universities money would be better spent on encouraging submission of preprints, a [Github](https://github.com) Enterprise/Education package and teaching researchers and faculty how to use social media like [twitter](https://twitter.com). Here is why I think that.

## Preprints

Submitting manuscripts to a preprint server such as [arxiv](http://arxiv.org/), [biorxiv](http://biorxiv.org/) or [peerj](https://peerj.com/preprints/) gives a researchers work possible visibility, and can result in immediate feedback to improve a work prior to submission, or as part of the peer review.

## Github

Much of our scientific output is generated as text. Whether it is lab notes, tables of data, draft manuscripts, or scientific scripts and programs, a lot of it is text. The Git version control system is well placed to handle iterations of text, and Github has become the defacto location for sharing version controlled text with others, and collaborating on it. Although I would imagine that it would take some encouragement, I think more researchers would use Git and Github if they knew about it, and had easy options to make Github repos private until they were ready to share their work. 

In addition to putting general text under version control, more researchers should be encouraged to use version control on any analysis scripts / programs that they write. This is becoming important across disciplines, not just in STEM fields. There is also more and more encouragement from journals and funding bodies to make underlying data and the processing of the data available. By putting data, and code on Github, moving from private collaboration to fully shared can be changed with the flick of a switch. Furthermore, `master` branches of repos are crawled by Google, making your text discoverable, making webpages for a group and on a project basis is relatively painless using [github-pages](https://pages.github.com), and repos can also have a wiki associated with them to allow further documentation.

## Twitter

I'm going to use [twitter](https://twitter.com) as a proxy for social media in general (blogs, facebook, twitter, and others), although I believe twitter combined with a blog is probably the best combination for science outreach. 

Having a blog to put announcements about when a new publication comes out, when a new presentation has been done (you are putting presentations on [figshare](https://figshare.com) or [slideshare](www.slideshare.net)), with links to the work in question. Twitter (and other social media platforms) allow quick communication to a wide audience that your research group has a new research output, and can allow engagement with other researchers in the field as well as non-experts, all of which improve ones visibility and provide opportunities for collaboration.

By the way, github-pages as mentioned above, also makes it easy to set up a [static blog](http://codecondo.com/7-static-site-generators-for-building-websites-blogs/) (non database blog site) for rather easy blogging.

## Open Science

All of the above encourages open science, sharing of results early and often. It does not have to, but as people get used to being able to share their work early and often, one would hope that this would become the norm, and it would lead to other researchers and possibly interested companies discovering applicable research for either collaboration, licensing, or simply re-use.

## How to implement

Now, if you've read this and you are not already doing these things, you might think this is all a lot of effort. Well, yes, it is. It takes time. This blog post didn't write itself, you know. My twitter use sometimes gets a bit excessive and addictive. And some of what I have described is rather technical in nature, and might take training to implement. For example, best practices around code and version control. I'm sure [Software Carpentry](http://software-carpentry.org/) would love to do workshops at UK for researchers (disclaimer: I have done the SC training, but haven't done a workshop yet). But overall, I know for me all of this (I'm speaking from experience and what I have observed in others) has been a plus to my research, not a minus.

So what say you, University of Kentucky? Why not try something different to make your researchers stand out to the world, and improve the scientific process?
